### ISSUE TITLE
Replace Celery with Scheduler

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#1]
#### Description

We'll be hosting this app on Heroku. They offer a [Scheduler add on](https://addons.heroku.com/scheduler) that works similar to cron jobs. We'll replace the Celery code with this Scheduler instead.
#### Tasks
- [ ] Remove celery.sh and celeryconfig.py
- [ ] Remove the celery dependency in tasks.py
- [ ] Set up [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler#scheduling-jobs) to run the update_projects function in tasks.py
