### ISSUE TITLE
Add a status column to projects

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#133]
#### Description
After being requested by several people using the CfAPI, we need to add a `status` column to projects.
Its been requested in #81 and in several conversations with Brigades.

The main use would be to show projects in different areas on Brigade websites.

Status could be `prototype`,`released`, `under development`. Whatever people want.

#### Tasks
- [x] Update the README
- [ ] Update all the linked GDocs under projects_list_url in the [Brigade Spreadsheet](https://docs.google.com/a/codeforamerica.org/spreadsheet/ccc?key=0ArHmv-6U1drqdGNCLWV5Q0d5YmllUzE5WGlUY3hhT2c&usp=drive_web#gid=0)
- [x] Update the Project model in app.py
- [x] Update run_update.py to read the status from a civic.json file

**Comment by jasonlally** [comment]
Have you incorporated this yet, is there an estimated timeline, if not?

**Comment by ondrae** [comment]
Hi @jasonlally We have not built it in yet.

We recently hired @tmaybe and he is helping us get the CfAPI where it needs to be. I'll introduce you both soon. We're almost done with bug fixes, so we're doing a planning session tomorrow about improvements. I'll have a timeline for you then.

**Comment by jasonlally** [comment]
Cool :+1: 

Thanks!

**Comment by hlprmnky** [comment]
I found this from the Civic Tech Issue Finder, and if it's still open I would like to take a crack at it. I've requested access to the brigade spreadsheet, and will present a PR as soon as I am able.

**Comment by hlprmnky** [comment]
I have submitted PR #201 for this issue - I still don't have access to the spreadsheet, but the code, tests, migration, and README update are all there. Cheers!

**Comment by ondrae** [comment]
We've got support for the `status` column in the api. Next up is to start collecting it from projects. There will be two ways we need to support:
* #203 Groups that have their projects listed in a csv will be able to add a `status` column.
* #204 Groups that use a GitHub org as their list, we will start pulling `status` from a civic.json file.

**Comment by tmaybe** [comment]
@jasonlally status is now supported in the API! The value can be read from project list spreadsheets and from a civic.json file in a GitHub project's root directory. [Here's an example](http://codeforamerica.org/api/projects/1305) of [a project](https://github.com/NYPDVisionZeroAccountability/compstat-vs-moving-violation-enforcement) with a status set from [its civic.json](https://github.com/NYPDVisionZeroAccountability/compstat-vs-moving-violation-enforcement/blob/master/civic.json). I'm leaving this issue open until the project list spreadsheets are updated, as per @ondrae's checklist above.
