### ISSUE TITLE
Too many Labels

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#151]
#### Description

I was digging in the database and found 50k labels. 45k of them didn't have an `issue_id` attaching them to an issue. Need to dig further to see how these are being made. They could be getting duplicated when issues are updated. They could be sticking around when issues are getting deleted.
#### Files

run_update.py
#### Task
- [ ] Research where the mysterious issues are coming from.
- [ ] Write tests to confirm.
- [ ] Plug the leak!
