### ISSUE TITLE
Add commenters list to open issues.

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#154]
#### Description

We should collect the avatars and names of the people involved in the discussion of the Civic Tech Issues.

@ashcrow did a [great pull request](https://github.com/codeforamerica/civic-issue-finder/pull/20) which shows the avatars of the people who have contributed code to the project.

@kborchers is [suggesting](https://github.com/codeforamerica/cfapi/issues/136#issuecomment-59638835) that it might be better to see the avatars of the people involved in the discussion.
#### Files

run_update.py, app.py
#### Tasks
- [ ] The owner of the issue is grabbed from [the issue itself](https://api.github.com/repos/codeforamerica/cfapi/issues/136) under `user`.
- [ ] Within [`get_issues()`](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L445) add another call to get the avatars and names of commenters. `https://api.github.com/repos/codeforamerica/cfapi/issues/136/comments` for example.
- [ ] Add a commenters column with JsonType to [the Issues model](https://github.com/codeforamerica/cfapi/blob/master/app.py#L321). 
- [ ] The result should be a commenters attribute list on the /issues endpoint. Something like:

```
{
  api_url: "http://codeforamerica.org/api/issues/9683",
  body: "Would be handy :)",
  commenters : [
    { 
      login: "ondrae",
      avatar_url: "https://avatars.githubusercontent.com/u/595778?v=2"
    },
    {
      login: "pmackay",
      avatar_url: "https://avatars.githubusercontent.com/u/115115?v=2"
    },
  ]
  html_url: "https://github.com/codeforamerica/cfapi/issues/136",
  id: 9683,
  labels: [ ... ],
  project_id: 1022,
  title: "Add avatar URL property to organization object"
},
```

**Comment by bsmithgall** [comment]
:+1: for this ! It would be hugely valuable to have all of this, though the sample shown above doesn't have a flag for the original opener, which would also be valuable I think (either in the list of commenters or as a top-level property).

**Comment by migurski** [comment]
Might we not lean on the Github API for this, with links to [issue comments](https://developer.github.com/v3/issues/comments/)? With our current update model, this seems like it would exhaust our Github API usage allowance quickly.

**Comment by bsmithgall** [comment]
At the very least, it would be nice to get the user who opened the issue and the total number of comments, and that comes for free with the original request.

**Comment by volkanunsal** [comment]
I'm in favor of just a summary of the number of comments on an issue, just enough to provide the information scent to the interested users to click through to go to Github.
