### ISSUE TITLE
Produce project_details.json files

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#18]
#### Description

The `civic-json-worker` began by producing flat files. We've since started using a database and API instead. There are lots of interesting possibilities made possible by producing and versioning the original project_details.json files though. These possibilities are described more in discussion of #9.

I've pulled the production of these files and their uploading to S3 into a [separate script](https://github.com/codeforamerica/civic-json-worker/blob/master/civic_json_transform.py). It currently doesn't work, I just copied and pasted all the relevant code over and it needs structure and clean up.
#### Tasks
- [ ] Rewrite civic_json_transform.py to actually produce json files.
- [ ] Have these files upload to S3.
- [ ] Set up Heroku Scheduler to run this script once a day.
- [ ] Figure out how to version them ...
