### ISSUE TITLE
Create a tags column on projects

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#193]
#### Description
We should add a `tags` column to the projects in the CfAPI. Right now we have `categories` and `type` which are intended to describe the category of work the project is in - transportation, health, open data - and the type of technology it is - web service, iOS app, API.

`tags` is simpler and will make searching easier to do, as well as making it more likely to be filled out by volunteers.

We can leave in the type and categories columns for now, to avoid any breaking changes.

#### Tasks
- [x] Update the docs
- [x] Update the Project model in app.py
- [x] Create database migrations
- [x] Write tests
- [x] Update run_update.py to to read these tags from project spreadsheets and civic.json files

**Comment by lorenanicole** [comment]
Working on it :dancer: :+1:

**Comment by tmaybe** [comment]
Thanks for pitching in @lorenanicole! I'm working on reading the civic.json file in [this branch](https://github.com/codeforamerica/cfapi/tree/read-civic-json-%23205) and expect to have it done on Monday, so hold off on that particular aspect of this issue if you want to take advantage of that work.

**Comment by tmaybe** [comment]
(to be clear, I'll be reading *status* out of civic.json in that branch, not tags, but once the process is in place it'll be easy to read other details from the file)

**Comment by lorenanicole** [comment]
@tmaybe sounds like a plan :+1:

**Comment by tmaybe** [comment]
hey @lorenanicole, in 2a3ec45b9b6025ddefef7c1023ee3fcf38b7bd65, the pull request we just merged, we've added the ability to read and store values from a civic.json file. Check out the `update_project_from_civic_json` function in `run_update.py`, and let me know if you have any questions.

**Comment by tmaybe** [comment]
Hi @lorenanicole, I'm going to work on integrating tags into the API today. If you've done any work toward this goal, or would like to collaborate on the effort in some way, let me know! I don't want to duplicate any effort you've already made.

**Comment by tmaybe** [comment]
work is happening in [this branch](https://github.com/codeforamerica/cfapi/tree/add-tags-to-projects-%23193)
