### ISSUE TITLE
Write documentation on status

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#213]
We now support `status` in the CfAPI. We need to let Brigades know. Tell the Brigades how to get the status included.

#### Tasks
- [ ] Write good docs on how get `status included.
- [ ] Tell Brigades about them
- [ ] Work with each Brigade to get `status` included.
