### ISSUE TITLE
Add "created_at" and "updated_at" to Issues

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#218]
#### Description
We should add these two time stamps to Issues. Doing so will:
* Allow a user to change how issues are returned using a sort_by parameter. #167 #216 
* Sorting by "created_at" is more stable than returning by id
* Sorting by "updated_at" lets us just find the most active issues.
* Make it easier for @sbenthall to start his civic issues analysis.

#### Files
app.py, run_update.py

#### Tasks
- [ ] Add "created_at" and "updated_at" to [Issue](https://github.com/codeforamerica/cfapi/blob/master/app.py#L394)
- [ ] Pull in theses values during run_update's [get_issues](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L580)
- [ ] Adjust some run_update_tests to make sure the time stamps are included.

**Comment by sarunac** [comment]
I do see "created_at" and "updated_at" in the output of 
http://www.codeforamerica.org/api/issues/14636. Do you specifically want to add these two columns to Issue class?

**Comment by ondrae** [comment]
Yeah, adding these timestamps to the Issue class is whats needed. The ones you see are associated with the parent Project.

**Comment by tmaybe** [comment]
cosed with PR #265
