### ISSUE TITLE
Make CfAPI easy to set up for other groups

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#226]
#### Description

We've started getting requests for the CfAPI to be used by other groups.
* Public Media Stations - https://github.com/melodykramer/publicmedia#repos by @melodykramer
* Regional Planning Agencies - https://github.com/buckleytom/RegionalPlanners by @buckleytom

We should start making it easy for others to set it up themselves.

#### Tasks
- [ ] Add a guide on setting up to the current [installation instructions](https://github.com/codeforamerica/cfapi#installation).
- [ ] Make a template organization information sheet for people to copy.
- [ ] Move the [org_source.csv](https://github.com/codeforamerica/cfapi/blob/master/org_sources.csv) to be an environmental variable.
- [ ] Add info to the [deployment](https://github.com/codeforamerica/cfapi#deployment) section about adding `python run_update.py` to the Heroku Scheduler addon.
- [ ] Can they just fork the Heroku app somehow?
- [ ] Also point people to new guides on how to set up the [projects powered by the CfAPI](https://github.com/codeforamerica/cfapi#projects-powered-by-the-cfapi) with their new version.

**Comment by ondrae** [comment]
We've got examples of a publicmedia-cfapi up:
http://publicmedia-cfapi.herokuapp.com/api/
http://publicmedia-website.herokuapp.com/brigade/
https://publicmedia-issues.herokuapp.com/geeks/civicissues/widget

**Comment by buckleytom** [comment]
thanks @ondrae
