### ISSUE TITLE
Add a /history endpoint

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#229]
#### Description
One of our goals is to grow the number of people participating in the civic tech movement. We need to be able to show this growth. We should be able to compare current participation against past.

`http://codeforamerica.org/api/organizations/history`
```
{
  current_total : 145,
  last_week : 142,
  last_month : 137,
  last_year : 107
}
```
Repeat for /projects, /issues, /stories, /events, and /contributors

#### How
We'll need to have a few new tables `org_history`, `project_history`, etc.

These will have separate jobs that populate them. They'll get the totals for each endpoint once each day. They will have the totals, the endpoint, and the date.

The views for the /history endpoint will then go get the data for those dates above.

#### Files
app.py for the new models, migrations

#### Tasks
- [ ] Create new models in app.py
- [ ] Create new migrations - https://github.com/codeforamerica/cfapi#migrations
- [ ] Create new routes in app.py
- [ ] Create new daily_update.py that will grab all the totals
- [ ] Tests for everything
- [ ] New daily task on Heroku to run daily_update.py

**Comment by ondrae** [comment]
We've got this now with Meetup Pro.
