### ISSUE TITLE
Add an /attendance endpoint

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#236]
#### Description
We've recently begun tracking attendance at Brigade events. These are posted to our private PeopleDB. We could securely pull out attendance data during our hourly run_update.py.

The Brigade core team members will be able to log into the peopledb to get the raw data, with people's names and emails. The CfAPI will only store an aggregate of each groups daily checkins.  An example response could be like
`/attendance`
```
[
  {
    "organization" : "Code-for-San-Francisco",
    "total" : 1000,
    "weekly" : {
      "2014 01" : 0,
      "2014 02" : 0,
      ...
     "2015 15" : 50,
     "2015 16" : 65
     }
  },
  ...
]
```

An attendance endpoint will allow us to build a public facing view of attendance data. Something like the graph we're usin gon the private peopledb view.
![screen shot 2015-07-10 at 12 17 09 pm](https://cloud.githubusercontent.com/assets/595778/8657965/bbf8cba6-2955-11e5-9e90-e2825ecb62bc.png)

We could make that graph embeddable to, much like the [civic issue finder](http://www.codeforamerica.org/geeks/civicissues/embed).

#### Files
run_update.py

#### Tasks
- [x] the CfAPI will need secure readonly access to the peopledb @migurski 
- [x] Write a query to aggregate the attendance data according to the schema above
- [x] Make a new `attendance` model with the schema above.
- [x] Make two new routes `/attendance` and `/<organizationid>/attendance`
- [x] Tests for the api and run_update.py
