### ISSUE TITLE
Gather weekly attendance from Meetup

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#239]
#### Description
We are building out attendance tools for the Brigades. One of the tools is to automatically pull in attendance from Meetup.com We should have the CfAPI gather Meetup.com attendance once a week.

We'll be basing our work off of @wbushey's https://github.com/OpenTwinCities/cfapi_attendance_sync
The weekly update can go like
```
    # Get all the meetup groups that we have permission to gather attendance for
    # for each group
        # get event ids for the last week
        # for each event
            # get attendance
                # for each attendee
                    # push to the checkin tool
```

We should also be able to control the timespan we collect attendance for. It would be cool to get attendance all the way back to the beginning.

#### Files
get_meetup_attendance.py

#### Tasks
- [ ] 
There is some prep work for us to even get [permission to access attendance](https://github.com/codeforamerica/brigade/issues/347#issuecomment-130091580).
- [x] Write tests for each step and command line timespan
- [x] make a new file called get_meetup_attendance.py
- [x] Add it to the Heroku Scheduler for the CfAPI
- [x] Change the MEETUP_KEY to be from our main Meetup account.

**Comment by ondrae** [comment]
Meetup sent me an email, informing me of a better way to do attendance through the API. 

```
Did you see the announcement of the newer simplified attendance api?

https://groups.google.com/d/msg/meetup-api/lRhFYAQDJFg/2OrbGop58MYJ

We've folded attendance info into /2/rsvps by letting members with the ability to take event attendance request an attendance_status in a /2/rsvps response. This no longer defaults attended. It's only present when a attendance was actually taken which I think is what you wanted here.

This also fits in better with our own new mobile attendance taking tools. In fact, our own apps will be using the same exact API.

The current attendance requesting API will soon be deprecated in favor of requesting attendance_status with /2/rsvps and any future RSVP listing endpoints.
```

**Comment by ondrae** [comment]
The new way they told me about doesn't work ...

**Comment by ondrae** [comment]
I'm going to pull the Meetup code and data out into something separate. https://github.com/codeforamerica/cfapi/issues/243
