### ISSUE TITLE
Add an /rsvps endpoint

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#243]
#### Description
We had a good attempt at adding in Meetup data to our /attendance endpoint. Turns out that you can't get accurate attendance data out of meetup, they mark everyone as attended by default. They are [trying some new way](https://github.com/codeforamerica/cfapi/issues/239#issuecomment-130787460), but its dependent on some tool no one uses.

A side effect of this though is that we found out we can get Meetup event rsvp data for all of our groups going way back. This is a useful big vanity metric to have. Lets make it easy to brag about.

#### Files
run_update.py, app.py

#### Tasks
- [x] We need to remove the Meetup attendance code - roll back to https://github.com/codeforamerica/cfapi/commit/b22d54134d93c747b73eb3bc8ec27cc5c20c5725
- [x] Remove all the Meetup people and check ins from the PeopleDB.
- [x] Add an `rsvps` attribute on to our existing events in the CfAPI
- [x] Add an `/organizations/<org-id>/events/rsvps` endpoint onto each organization, with a similar schema to [/attendance](http://codeforamerica.org/api/organizations/Code-for-San-Francisco/attendance)
- [x] Add an `/events/rsvps` endpoint that aggregates all the orgs together.
