### ISSUE TITLE
Change our source of the Project last_updated attribute

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#245]
#### Description
@judy5000 noticed that a difference between our publish timestamp from the cfapi
![screen shot 2015-09-03 at 2 24 37 pm](https://cloud.githubusercontent.com/assets/595778/9671411/9676f20c-5247-11e5-90c2-9b0de72c0b5b.png)

and the timestamp from Github
![screen shot 2015-09-03 at 2 25 28 pm](https://cloud.githubusercontent.com/assets/595778/9671423/a7ed2b82-5247-11e5-9e5e-7dde7a4baa71.png)

A little assistance from @prashtx led to http://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at which describes the difference. `updated_at` refers to the repository object, while `pushed_to` means a commit.

For the CfAPI, we want whatever is the most recent.

We're using the [Last-Modified header attribute](https://developer.github.com/v3/#conditional-requests) from Github's API to supply the time stamp for our Project's `last_updated` value. As far as I can tell, this is the same as the `updated_at` attribute, meaning when was the repo object last updated.

We should switch that to use either `pushed_at` or `updated_at`, whichever is more recent. Then our `last_updated` will include either kind of updates.

#### Files
run_update.py

#### Tasks
- [x] Add a new function to find the most recent of the two timestamps, `updated_at` or `pushed_at`
- [x] Replace the source of our `last_updated` attribute with that new function at https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L437
- [x] Write tests in run_update_tests.py to check it all

**Comment by RandyMoore** [comment]
Pull request with fix submitted https://github.com/codeforamerica/cfapi/pull/255

**Comment by DaleMcGrew** [comment]
Hello @RandyMoore, @judy5000 and @ondrae, the problem still exists on http://codeforsanfrancisco.org/projects/ Projects (like "We Vote San Francisco") that have approved pull requests in the last 3 days (https://github.com/wevote/WeVoteServer) show up on the projects page has being last updated 4 months ago. Thank you.
