### ISSUE TITLE
Rewrite API

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#26]
#### Description

Flask-Restless has a few limitations we are up against. It depends on each Brigade having a numerical id. You can only return a single Brigade by using its id. http://civic-tech-movement.codeforamerica.org/api/organizations/1 

The syntax for using a string instead is really ugly. [http://civic-tech-movement.codeforamerica.org/api/organizations?q={"filters":[{"name":"name","op":"eq","val":"Code for San Francisco"}]}](http://civic-tech-movement.codeforamerica.org/api/organizations?q={"filters":[{"name":"name","op":"eq","val":"Code for San Francisco"}]})

We really only need four endpoints that either return multiple or single responses.
/organizations, /projects, /events, /stories

_Lets rewrite it ourselves!_
#### Files

app.py
#### Tasks
- [ ] Remove all flask-restless code.
- [ ] Write new routes for each of the wanted endpoints.
- [ ] /organizations should return all of the organizations.
- [ ] /organizations/Code for San Francisco should return just one.
- [ ] A organization should also have all of its two latest stories, projects, and events returned as well.
