### ISSUE TITLE
Add organization name to project search

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#260]
#### Description
From user testing: "First thing I did was type in Code for Denver. I got a weird list of projects."
That search only returned projects that had Code for Denver in the name or description of the project. It should also include any of Code for Denver's projects. 

Then you could do good searches like `/projects?q=Code+for+Denver+food` and get something useful.

#### Tasks
- [x] Add `organization_name` to the [search update trigger](https://github.com/codeforamerica/cfapi/blob/master/app.py#L400)
- [x] Write a new migration to include it. [An example](https://github.com/codeforamerica/cfapi/blob/master/migrations/versions/4f685c062cff_improved_project_search.py).
- [x] Add a test to ensure it works.
