### ISSUE TITLE
Add GitHub Org Url as an attribute to each organization

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#268]
#### Description
The CfAPI is becoming more closely aligned with GitHub as some of the most useful tools powered by it are the Issue Finder and Project Search. We should make the GitHub urls for each of our groups more obvious.

Also, GitHub has donated free upgraded accounts for all of our groups and needs an easier way to identify them.

#### Files
[Brigade Info Sheet](https://docs.google.com/spreadsheets/d/1cFswd6i-80f7rMKJzLOcJzr1Zb7gUukPkoi_I9MAdjQ/edit#gid=0), run_update.py, models.py

#### Tasks
- [ ] Add a column to the Brigade Info sheet called `GitHub_Url`
- [ ] Add an `GitHub_Url` attribute to the [Organization model](https://github.com/codeforamerica/cfapi/blob/master/models.py#L77)
- [ ] Pull in this new column using run_update.py
- [ ] Write some tests to check for this new `GitHub_url` attribute for organizations
