### ISSUE TITLE
Get the last commit status for each project from GitHub

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#298]
#### Description
Continuing the discussion from https://github.com/codeforamerica/brigade/pull/435#issuecomment-171398472. In order to improve the [Project Monitor](http://www.codeforamerica.org/brigade/projects/monitor), we should start including the projects testing status in the CfAPI.

We're already making four GitHub requests during the hourly update, lets include another. We may need to do another request first to find out what the default branch is.

We'll also need to add a new attribute on to Project of `test_status` or `last_commit_status` or something like that.

#### Files
models.py, app.py, run_update.py, tests/

#### Tasks
- [x] Write a test to find the new `last_commit_status` on projects
- [x] Add the new attribute to [the Project model](https://github.com/codeforamerica/cfapi/blob/master/models.py#L283)
- [x] Write a new test in test/updater that test us asking github for the last commit status
- [x] Add the real request code to the end of [update_project_info](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L478) in run_update.py
- [x] Add the new attribute to [the docs](https://github.com/codeforamerica/cfapi/blob/master/templates/index.html)
