### ISSUE TITLE
Multiple lists of Organizations

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#60]
#### Description

Currently, we use [one master list](https://docs.google.com/a/codeforamerica.org/spreadsheet/ccc?key=0ArHmv-6U1drqdGNCLWV5Q0d5YmllUzE5WGlUY3hhT2c&usp=drive_web#gid=0) of Organizations. We should instead have multiple lists of organizations of different types. We could have a list of all the Fellowship teams, a list of all of our non-profits partners, a list of all of our funders, a list of all the Code for All groups. Each of these will be in a different GDoc with different editing permissions.
#### Files

run_update.py
#### Tasks
- [x] Have run_update.py read from a list of gdoc links, instead of just the one.
- [x] Create Google Spreadsheets for each type of organization we want to include in the API.
- [x] The different types of orgs would be indicated in the `type` column at /organizations.
