### ISSUE TITLE
Make new endpoint /issues

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#85]
#### Description

We want to start collecting all the open issues on GitHub projects. We want to eventually make these issues searchable. These should all be accessible at a new endpoint called `/issues`. 

When run_update.py loops through all of the GitHub projects, it should make another call to collect the GitHub Issues. It only returns the open issues by default.
#### Example

`https://api.github.com/repos/codeforamerica/cfapi/issues`

If we want to get only certain issues, such as hack.
`https://api.github.com/repos/open-austin/austin-recycles/issues?label=hack`
#### Files

run_update.py, app.py
#### Tasks
- [ ] Make a new table for issues. We'll want to save the title, the html_url, the labels, the body.
- [ ] Add another function to run_update.py that grabs the issues for each project.
- [ ] Add a new /issues route to app.py
